export const quotes = [
  "Time is gold.",
  "Use time wisely.",
  "Time waits for no one.",
  "Value your time.",
  "Time is precious.",
  "Time flies, use it well.",
  "Time is an asset.",
  "Invest time wisely.",
  "Make time count.",
  "Time is everything.",
  "Time should be welll spent.",
  "Time is valuable.",
  "Lost time is lost.",
  "Time counsels best.",
  "Manage your time.",
  "Time is key.",
  "Every second counts.",
  "Time is priceless.",
  "Time is true wealth.",
  "Start now.",
  "Time is non-renewable.",
  "Essence of life.",
  "Time equalizes.",
  "Respect time.",
  "Time is a gift.",
  "Clock is ticking.",
  "Time is Ultimate luxury.",
  "Time is a valuable asset.",
  "Guard time jealously.",
  "Time is a relentless force.",
  "The essence of life is time.",
  "Don't waste time.",
  "Time is precious commodity.",
  "Time is Ultimate investment.",
  "Every minute matters.",
  "Time is the currency of life.",
  "Time is the Ultimate capital.",
  "Time is immeasurable.",
  "Time is the silent architect.",
  "Time is the ultimate arbiter.",
  "Make time, don't find time.",
  "Schedule wisely, live happily.",
  "Don't kill time, use it to live.",
  "Use your time, don't lose it.",
  "Time is God's gift to you.",
  "Time is humanity's greatest treasure.",
  "Time is the essence of strategy.",
  "Time is a friend, treat it kindly.",
  "Don't let time slip away, grasp it.",
  "Time is a test, pass it with flying colors.",
  "Use your time to make a difference.",
  "Time is a journey, enjoy the ride.",
  "Make time for what matters most.",
  "Time is a gift, unwrap it with care.",
  "Don't let time control you, control it.",
  "Time is a puzzle, solve it wisely.",
  "Every second is a new chance.",
  "Time is a river, flow with it wisely.",
  "Make the most of every moment.",
  "Time is a mirror, reflect on it wisely.",
];
